name: firebase_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3
  dio: ^5.3.2
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  google_sign_in: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
